# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/binding_ninja/all/binding_ninja.rbi
#
# binding_ninja-0.2.3

module BindingNinja
  def auto_inject_binding(*arg0); end
  def auto_inject_binding_options; end
  def included(klass); end
  def inherited(klass); end
  def self.extended(klass); end
end
