# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/bitarray/all/bitarray.rbi
#
# bitarray-1.3.0

class BitArray
  def [](position); end
  def []=(position, value); end
  def byte_position(position); end
  def each; end
  def each_byte; end
  def field; end
  def initialize(size, field = nil, reverse_byte: nil); end
  def size; end
  def to_s; end
  def total_set; end
  include Enumerable
end
