# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rspec-parameterized/all/rspec-parameterized.rbi
#
# rspec-parameterized-0.5.0

module RSpec
end
module RSpec::Parameterized
end
class RSpec::Parameterized::Arg
  def apply(obj); end
end
class RSpec::Parameterized::RefArg < RSpec::Parameterized::Arg
  def apply(obj); end
  def initialize(symbol); end
  def inspect; end
end
class RSpec::Parameterized::LazyArg < RSpec::Parameterized::Arg
  def apply(obj); end
  def initialize(&block); end
  def inspect; end
end
module RSpec::Parameterized::HelperMethods
  def lazy(&block); end
  def ref(symbol); end
  def self.applicable?(arg); end
end
module RSpec::Parameterized::ExampleGroupMethods
  def define_cases(parameter, *args, &block); end
  def params_inspect(obj); end
  def set_parameters(arg_names, &b); end
  def set_verbose_parameters(&block); end
  def where(*args, &b); end
  def with_them(*args, &b); end
end
class RSpec::Parameterized::ExampleGroupMethods::Parameter
  def arg_names; end
  def block; end
  def initialize(arg_names, &block); end
end
module RSpec::Core
end
class RSpec::Core::ExampleGroup
  extend RSpec::Parameterized::ExampleGroupMethods
end
